### ISSUE TITLE
wish: replace SHA1 with SHA256

### ISSUE THREAD

**Issue by markstos** [kevincobain2000/action-cache-http#12]
SHA1 used here is known to be vulnerable to collision attacks.

While it's not clear if there's a practical way to create an exploit due to this projects use of SHA1, it's generally recommended to be sunsetted in favor of SHA265 or new ( https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html ).

The good news is that `openssl sha1` can simply be swapped for `opensl sha256`. Also, `coreutils` provides the `sha1sum` binary as well as `sha256sum`. So there should be no additional dependencies. 

In a simple test, there was a not a significant performance difference using SHA256. 

Still, the change might quality as a major version bump because it will cause cache misses during the first run due to changing cache keys.

**Comment by kevincobain2000** [comment]
In terms of security, both are not being used in order to make the tar name secure or not vulnarable to collision attacks. A collision attack right now can simply be done from a post request for any org/repo, since the backend API is not secure. As this tool is developed for the enterprise self-hosted runners, which is not likely to have any bad actors within a company.

These are just to be able to generate a unique id for the file. If worried about a collision attack then checking at the backend that the origin request belongs to the rightful org and repo, will be a bullet proof solution.

Sample:

https://github.com/rakutentech/code-coverage-dashboard/blob/26a658567a62ca514e910857d49a0d58fc1b03e0/server/services/github_oauth_service.go#L24-L50

What the above code does is - Obtains the github_token from the GHE actions. And then verifies that the token belongs to the org/repo, and not someone making a POST request from another source and trying to override the asset.

**Comment by markstos** [comment]
Thanks for clarifying there doesn't appear to be security issue here. The change still seems like future-proofing with little downside.  

I expect SHA-256 will live on longer than SHA-1, while using SHA-256 adds no new dependencies and apparently little noticeable performance difference.

I'm not sure I see what benefits are in favor of using SHA-1 instead.

**Comment by kevincobain2000** [comment]
It's fine to have it. It won't break anything on the action, just that all the existing cache would be busted automatically.

**Comment by kevincobain2000** [comment]
https://github.com/actions/cache/issues/505#issuecomment-1123435993
